name: Pytest CI

on: [push]

env:
  DAY_OF_WEEK: Monday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Update APT and Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tini git build-essential libleveldb-dev ca-certificates
          sudo apt clean
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install Dolt
        run: sudo bash -c 'curl -L https://github.com/dolthub/dolt/releases/latest/download/install.sh | bash'
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ${{ github.workspace }}/src
      - name: Run Bash Tests
        run: ${{ github.workspace }}/scripts/test.sh
      - name: Run Pytest
        run: pytest ${{ github.workspace }}/src
